version: '3.3'

volumes:
  backend_static:

services:
  backend:
    image: tenthteam/backend
    command: sh -c "python manage.py collectstatic && daphne -b 0.0.0.0 -p 8000 config.asgi:application"
    env_file: ./.env
    volumes:
      - backend_static:/app/static
  nginx:
    image: nginx:1.19.3
    volumes:
       - backend_static:/backend_static
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - backend
