version: '3.3'

services:
  db:
    image: postgres:13-alpine
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env.example
    restart: always
  backend:
    build: ../backend
    env_file:
      - .env.example
    volumes:
      - ../backend/:/app/
      - backend_static:/app/static
    command: >
      sh -c "python manage.py collectstatic --no-input &&
             sleep 3 && 
             python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  nginx:
    image: nginx:1.19.3
    volumes:
      - backend_static:/backend_static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8000:80"
    depends_on:
      - backend

volumes:
  postgres:
  backend_static:
