version: '3.3'

volumes:
  backend_static:

services:
  backend:
    build: ../backend
    env_file: ../.env
    volumes:
      - backend_static:/app/static
      - ../backend/:/app/
  nginx:
    image: nginx:1.19.3
    volumes:
       - ./nginx.conf:/etc/nginx/conf.d/default.conf
       - backend_static:/backend_static
    ports:
      - "80:80"
    depends_on:
      - backend
