# Generated by Django 4.2.10 on 2024-02-24 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AmbassadorGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название цели')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название программы')),
            ],
        ),
        migrations.CreateModel(
            name='Ambassador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Полное имя')),
                ('gender', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
                ('country', models.CharField(max_length=100, verbose_name='Страна')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('postal_code', models.CharField(max_length=20, verbose_name='Индекс')),
                ('email', models.CharField(max_length=255, verbose_name='Адрес проживания')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Номер телефона')),
                ('telegram', models.CharField(max_length=100, verbose_name='Ник в телеграме')),
                ('edu', models.TextField(max_length=1000, verbose_name='Образование')),
                ('work', models.TextField(max_length=1000, verbose_name='Место работы')),
                ('study_goal', models.TextField(max_length=1000, verbose_name='Цель обучения')),
                ('blog_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка на блоги')),
                ('clothing_size', models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=3, verbose_name='Размер одежды')),
                ('shoe_size', models.CharField(max_length=50, verbose_name='Размер обуви')),
                ('additional_comments', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Дополнительная информация')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('paused', 'На паузе'), ('not_ambassador', 'Не амбассадор'), ('pending', 'Уточняется')], default='pending', max_length=50, verbose_name='Статус амбассадора')),
                ('reg_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('amb_goal', models.ManyToManyField(related_name='ambassadors', to='ambassadors.ambassadorgoal', verbose_name='Цель амбассадорства')),
                ('ya_edu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ambassadors.trainingprogram', verbose_name='Программа обучения')),
            ],
        ),
    ]
