# Generated by Django 4.2.10 on 2024-03-02 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandiseshippingrequest',
            options={'verbose_name': 'Заявка на отправку мерча', 'verbose_name_plural': 'Заявки на отправку мерча'},
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Промокод')),
                ('status', models.CharField(choices=[('active', 'Активный'), ('non-active', 'Неактивный')], default='active', max_length=10, verbose_name='Статус промокода')),
                ('ambassador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promo_code', to='ambassadors.ambassador', verbose_name='Амбассадор')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
