# Generated by Django 4.2.10 on 2024-03-07 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ambassadors', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchandise',
            options={'verbose_name': 'Мерч', 'verbose_name_plural': 'Мерчи'},
        ),
    ]
