# Generated by Django 4.2.10 on 2024-03-08 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="merchandise",
            options={"verbose_name": "Мерч", "verbose_name_plural": "Мерч"},
        ),
        migrations.AlterField(
            model_name="merchandiseshippingrequest",
            name="ambassador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="merch_shipping_requests",
                to="ambassadors.ambassador",
                verbose_name="Амбассадор",
            ),
        ),
        migrations.AlterField(
            model_name="merchandiseshippingrequest",
            name="name_merch",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                to="ambassadors.merchandise",
                verbose_name="Название мерча",
            ),
        ),
    ]
