# Generated by Django 4.2.10 on 2024-02-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Content",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Имя и Фамилия"),
                ),
                (
                    "telegram",
                    models.CharField(max_length=100, verbose_name="Ник в телеграме"),
                ),
                (
                    "link",
                    models.CharField(max_length=200, verbose_name="Ссылка на контент"),
                ),
                ("guide", models.BooleanField(verbose_name="В рамках Гайда?")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новая публикация"),
                            ("approved", "Одобрена"),
                            ("rejected", "Не одобрена"),
                        ],
                        default="new",
                        max_length=50,
                        verbose_name="Статус контента",
                    ),
                ),
                (
                    "created_date",
                    models.DateField(auto_now_add=True, verbose_name="Дата создания"),
                ),
                (
                    "ambassador",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ambassadors.ambassador",
                    ),
                ),
            ],
        ),
    ]
