# Generated by Django 4.2.10 on 2024-03-09 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ambassadors", "0002_alter_merchandise_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="content",
            name="comment",
            field=models.TextField(
                blank=True,
                max_length=200,
                null=True,
                verbose_name="Комментарий менеджера",
            ),
        ),
    ]
